from __future__ import annotations

from homeassistant.const import Platform

DOMAIN = "cyberpower_pdu"

PLATFORMS: tuple[Platform, ...] = (
    Platform.SENSOR,
    Platform.SWITCH,
    Platform.BUTTON,
)

CONF_AUTH_KEY = "auth_key"
CONF_AUTH_PROTOCOL = "auth_protocol"
CONF_COMMUNITY = "community"
CONF_CONTEXT_NAME = "context_name"
CONF_PRIVACY_KEY = "privacy_key"
CONF_PRIVACY_PROTOCOL = "privacy_protocol"
CONF_RETRIES = "retries"
CONF_SNMP_VERSION = "snmp_version"

SNMP_V1 = "v1"
SNMP_V2C = "v2c"
SNMP_V3 = "v3"
SNMP_VERSIONS = (SNMP_V3, SNMP_V2C, SNMP_V1)
DEFAULT_SNMP_VERSION = SNMP_V2C

AUTH_NONE = "none"
AUTH_MD5 = "md5"
AUTH_SHA = "sha"
AUTH_SHA224 = "sha224"
AUTH_SHA256 = "sha256"
AUTH_SHA384 = "sha384"
AUTH_SHA512 = "sha512"
AUTH_PROTOCOLS = (
    AUTH_SHA,
    AUTH_SHA256,
    AUTH_SHA512,
    AUTH_SHA384,
    AUTH_SHA224,
    AUTH_MD5,
    AUTH_NONE,
)

PRIVACY_NONE = "none"
PRIVACY_DES = "des"
PRIVACY_3DES = "3des"
PRIVACY_AES = "aes"
PRIVACY_AES192 = "aes192"
PRIVACY_AES256 = "aes256"
PRIVACY_PROTOCOLS = (
    PRIVACY_AES,
    PRIVACY_AES256,
    PRIVACY_AES192,
    PRIVACY_3DES,
    PRIVACY_DES,
    PRIVACY_NONE,
)

DEFAULT_AUTH_PROTOCOL = AUTH_SHA
DEFAULT_COMMUNITY = "private"
DEFAULT_PORT = 161
DEFAULT_PRIVACY_PROTOCOL = PRIVACY_AES
DEFAULT_RETRIES = 1
DEFAULT_SCAN_INTERVAL = 30
DEFAULT_TIMEOUT = 2
DEFAULT_OUTLET_COUNT = 8

OUTLET_STATE_ON = 1
OUTLET_STATE_OFF = 2
OUTLET_COMMAND_ON = 1
OUTLET_COMMAND_OFF = 2
OUTLET_COMMAND_REBOOT = 3

DEVICE_NAME = "CyberPower PDU"
